# Generated by Django 5.0.6 on 2025-06-18 07:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("heading", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField()),
                ("keywords", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url_slug", models.SlugField(max_length=200, unique=True)),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.CharField(max_length=255)),
                ("keywords", models.CharField(max_length=255)),
                ("body", ckeditor.fields.RichTextField()),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=255)),
                ("created_on", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("mode", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
