# Generated by Django 5.0.6 on 2025-06-18 07:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("heading", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField()),
                ("keywords", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
                ("challenges", ckeditor.fields.RichTextField()),
                ("vision_mission", ckeditor.fields.RichTextField()),
                ("services", ckeditor.fields.RichTextField()),
                ("team", ckeditor.fields.RichTextField()),
                ("team_image", models.ImageField(upload_to="images/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facts", models.CharField(max_length=255)),
                ("percentage", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("heading", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField()),
                ("keywords", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
                ("challenge", ckeditor.fields.RichTextField()),
                ("approach", ckeditor.fields.RichTextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("query", models.CharField(blank=True, max_length=1000)),
                ("receive_newsletter", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.TextField(blank=True, max_length=150)),
            ],
        ),
    ]
